export default {
  rid: 'random',
  cv: 'version lib',
  c: 'client api', // id
  url: 'location url',
  d: 'duration (?)',
  i: 'sendOptions (?)',
  j: 'tls.length (?)',
  cbd: 'config callbackData',
  cr: 'document.referrer',
  k1: 'cpuClass',
  k2: 'language',
  k3: 'colorDepth',
  k4: 'deviceMemory',
  k5: 'screenResolution',
  k6: 'availableScreenResolution',
  k7: 'hardwareConcurrency',
  k8: 'timezoneOffset',
  k9: 'timezone',
  k10: 'sessionStorage',
  k11: 'localStorage',
  k12: 'indexedDb',
  k13: 'openDatabase',
  k15: 'platform',
  k16: 'plugins',
  k17: 'canvas',
  k18: 'adBlock',
  k19: 'touchSupport',
  k20: 'fonts',
  k21: 'audio',
  k22: 'plugins enabled',
  k23: 'browser build',
  k24: 'eval.toString().length (?)',
  k25: 'Error.toSource() (?)',
  k26: 'webdriver',
  k27: 'navigator.vendor',
  k28: 'chromium',
  k29: 'permissions notifications',
  k30: 'run Selenium',
  k31: 'incognito (?)',
  k32: 'cookie support',
  k33: 'canvas manipulation (?)',
};
